services:
  - type: web
    name: anubhuti-ii-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        sync: false
